# This workflow updates the version text, then builds and attaches a build to the release that triggered it
name: 'Create Release'

# Controls when the action will run. 
on:
  release:
    types: [ released, prereleased ]
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Updates the version txt, and sets which version file is used depending on whether event that triggered workflow was a release or prerelease
      - name: Update version.txt version
        run: |
          if [[ "${{ github.event.action }}" == "released" ]]; then
            VERSION_FILE="version.txt"
            echo "VERSION_FILE=version.txt" >> $GITHUB_ENV
          else
            VERSION_FILE="version_prerelease.txt"
            echo "VERSION_FILE=version_prerelease.txt" >> $GITHUB_ENV
          fi
          
          echo "Updating:" $VERSION_FILE
          echo '${{ github.event.release.tag_name }}' | sed 's/[^0-9]*//' > CompilePalX/$VERSION_FILE
          
      # Updates version.txt on Github
      - name: Update version.txt on GitHub
        uses: test-room-7/action-update-file@v1.4.0
        with:
            file-path: CompilePalX/${{ env.VERSION_FILE }}
            commit-msg: Update version
            github-token: ${{ secrets.GITHUB_TOKEN }}
